services:
  stats-server:
    build: stats/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=statsDb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 5s

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      stats-db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://user:password@stats-db:5432/postgres -v ON_ERROR_STOP=1 <<-EOSQL
        
        CREATE TABLE IF NOT EXISTS stats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app VARCHAR(255) NOT NULL,
        uri VARCHAR(255) NOT NULL,
        ip VARCHAR (255) NOT NULL ,
        created_date TIMESTAMP NOT NULL
        );
        EOSQL

